### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by thos91** [LastStarDust/Analysis#1]
Trying to compile the code using cmake, I get the following error :

[ 62%] Linking CXX shared library libwgGainCalib.so
/home/tmueller/WAGASCI/Analysis/process/wgOnlineMonitor/libwgOnlineMonitor.cpp:19:10: fatal error: pyrame.h: No such file or directory
   19 | #include "pyrame.h"
      |          ^~~~~~~~~~
compilation terminated.

Looks like pyrame.h is missing. Is it important, should we just comment the line out ?

**Comment by thos91** [comment]
Commenting everything in the dedicated CMakeList prevents compilation of the wgOnlineMonitor and other processes are compiled without any troubles (it seems)

**Comment by LastStarDust** [comment]
Dear Thomas,
thank you for the bug report. It seems that you already found a solution. Yes, your guess is right. I forgot to remove some still in development components from the release branch. Now I have released a [hotfix](https://github.com/LastStarDust/Analysis/releases/latest) that addresses the issue.
Basically you only need to compile the `wgDecoder` and maybe the `wgMakeHist` programs. You can select what to compile and what not in the `Analysis/process/CMakeLists.txt` file.
Closing this issue as solved.
